export const USER_STATE_INIT = 'INIT';
export const AUTHORIZATION_TYPE = 'Bearer';

export const USER_ROLE_APP_ADMIN = 'APP_ADMIN';
export const USER_ROLE_ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN';
export const USER_ROLE_ORGANIZATION_MANAGER = 'ORGANIZATION_MANAGER';
export const USER_ROLE_ORGANIZATION_USER = 'ORGANIZATION_USER';
